# Welcome to Serverless!
#

service: test-conductor

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: dev
  deploymentBucket: s37-dev-lambda
  deploymentPrefix: serverless # S3://s37-dev-lambda/serverless/<service name>/<stage>

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.handleHelloEvent
  errorEvent:
    handler: handler.handleErrorEvent

stepFunctions:
  stateMachines:
    hellostepfunc1:
      ${file(includes/state-machine.yml)}

